added users and items functionality according to the FT13
Shmakls/java-shareit pull request #2
Opened 2022-07-22 07:18 UTC by Shmakls

Евгений, здравствуйте!
Добавил функционал User и Item фичей по ФЗ13.

2022-07-23 14:37 UTC, EugeneLenkevich requested changes
Привет, Артур, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-07-23 14:37 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/controllers/ItemController.java
> +        if (!userService.isExists(userId) || userId == null) {
По своей сути контроллер только обрабатывает (маршрутизирует сервисам) запросы, а тут же в контроллере выполняется некоторая бизнес-логика, ее лучше перенести в сервис, иначе логика размазывается по нескольким классам :)

2022-07-23 14:37 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/ItemValidator.java
> +        if (description == null || !StringUtils.hasText(description)) {
StringUtils.hasText нормально отрабатывает в случае если передан null, дополнительно проверять на нулл не надо :)

2022-07-24 07:31 UTC, Shmakls commented on src/main/java/ru/practicum/shareit/item/controllers/ItemController.java
> +        if (!userService.isExists(userId) || userId == null) {
Вывел обработку этого API в отдельный класс CommonService.

2022-07-24 15:29 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-07-24 17:00 UTC, merged