added Booking functional FT14 version 1
Shmakls/java-shareit pull request #3
Opened 2022-08-08 19:04 UTC by Shmakls

Евгений, здравствуйте!
Тяжело даются что-то такие большие проекты пока что, я забываю что я делал 2 дня назад. Посмотрите, пожалуйста, не сильно ли там всё плохо.

2022-08-09 12:42 UTC, EugeneLenkevich requested changes
Привет, Артур, спасибо за PR

В целом все супер, наверное заметил что с JPA гораздо проще работать чем с голым SQL :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

2022-08-09 12:42 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (bookingChecker != null && bookingChecker.getStatus().equals(BookingStatus.REJECTED)) {
bookingChecker.getStatus() == BookingStatus.REJECTED

Вроде как для enum можно и так :)

2022-08-09 12:42 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            bookings.addAll(bookingRepository.findBookingsByItemId(item));
А не получится в качестве параметра передать список id-шников, так будет один запрос вместо целой кучи :)

2022-08-09 12:42 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/dto/Booker.java
> +    private final Integer id;
Какой то странный класс с одним id :)

2022-08-09 12:42 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +        if (booking.getId() != null) {
Ну ка, а как тебе вот такой код :)

Optiona.ofNullable(booking.getId())
  .ifPresent((id) ->{  bookingDto.setId() })

или даже вот так

Optiona.ofNullable(booking.getId())
 .ifPresent(bookingDto::setId)

2022-08-10 07:30 UTC, Shmakls commented on src/main/java/ru/practicum/shareit/booking/dto/Booker.java
> +    private final Integer id;
Согласен, чухонь полная, но
![TestGetBooking](https://user-images.githubusercontent.com/90335552/183841500-2dabbc96-2a2e-4f9b-9393-2fa89cd09a4d.jpg)

2022-08-10 13:21 UTC, Shmakls commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            bookings.addAll(bookingRepository.findBookingsByItemId(item));
да, и правда так можно. Первый раз у меня не получилось, оказывается надо было добавить в конце In.

2022-08-10 13:35 UTC, Shmakls commented
В целом полегче с кастомной репой, но когда не понимаешь как устроен метод save(S entity), который и update же, пришлось много помучиться чтобы получился нормальный update. 
Хотел попробовать сортировку бронирований переложить на бд, но добавление в конце названия запросного метода OrderByStartDesc или Asc привели к тому что начали не проходить тесты и сортировка получилась какая-то кривая. Оставил пока вариант с компаратором.
В целом по приложению смущает структура: Сервисы сущностей получились лишней прокладкой, которая по сути не имеет функционала, по-моему мнению было бы гораздо проще и понятней переложить всё на CommoService. К тому же я не понял некоторых "советов ментора", например: 
![Совет от ментора](https://user-images.githubusercontent.com/90335552/183914541-ea1a1613-f519-40f2-b26a-4863e3ffd5cf.jpg)
Зачем давать доступ к хранилищу нескольким сервисам? Линейна структура гораздо проще для понимания других, а связи пусть осуществляет один общий Сервис.
Ну, как-то так.

2022-08-10 17:50 UTC, EugeneLenkevich commented
Ну это только кажется что сервисы не нужны. Они бывают не нужны в случае, когда логика примитивна, например в справочниках. В реальном проекте в сервисах содержится куча логики, просто пример плюшевый, учебный. Вообще сама сущность в сервисе может собираться из нескольких репозиториев, может быть там будут запросы к другим вэб-сервисам, отправка каких то асинхронных сообщений, сложные расчеты каких то параметров и тд и тп
Потому единый сервис не гут, просто  у нас пример тривиальный :)

2022-08-10 17:53 UTC, EugeneLenkevich approved these changes
Все супер, спасибо!

2022-08-10 18:18 UTC, merged